"""add unit to variables

Revision ID: 432297eb228c
Revises: d88bf1ef7611
Create Date: 2026-04-14 23:53:30.777460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432297eb228c'
down_revision = 'd88bf1ef7611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variables', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
