"""add containers and variable container_id

Revision ID: ff99c29c690e
Revises: 432297eb228c
Create Date: 2026-04-14 23:58:37.127254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff99c29c690e'
down_revision = '432297eb228c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('variables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'containers', ['container_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variables', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('container_id')

    op.drop_table('containers')
    # ### end Alembic commands ###
